#!/usr/bin/env node
/**
 * `responsive-overflow-tests init` — scaffolds the wiring so a fresh project
 * can go from install to a green overflow run.
 *
 * Design rules:
 *  - Exactly one file the user ever edits: responsive-overflow-tests.config.*
 *  - Nothing is written that isn't announced on stdout.
 *  - Never overwrites an existing file, so re-running is safe.
 *  - Node built-ins only, no runtime dependencies.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const DOCS = "https://github.com/CyberPunkCodes/responsive-overflow-tests/blob/main/ADVANCED.md";
const ARTIFACT_DIR = ".playwright/";

type Lang = { ext: "ts" | "js" | "mjs"; importSuffix: string };

/**
 * TypeScript if there's a tsconfig (Playwright transpiles it natively).
 * Otherwise ESM JavaScript — `.js` when the project is already `type: module`,
 * `.mjs` when it isn't, since `.mjs` is ESM regardless of the package type.
 */
function detectLang(cwd: string): Lang {
  if (existsSync(resolve(cwd, "tsconfig.json"))) return { ext: "ts", importSuffix: "" };

  let isModule = false;
  try {
    const pkg = JSON.parse(readFileSync(resolve(cwd, "package.json"), "utf8")) as { type?: string };
    isModule = pkg.type === "module";
  } catch {
    // No/unreadable package.json — fall through to .mjs, which is always ESM.
  }

  return isModule ? { ext: "js", importSuffix: ".js" } : { ext: "mjs", importSuffix: ".mjs" };
}

const CONFIG_BASENAME = "responsive-overflow-tests.config";

const configTemplate = (): string => `import { defineConfig } from "responsive-overflow-tests";

export default defineConfig({
  // ── Where your site runs ──────────────────────────────────────────────
  // The port your local dev server listens on.
  //   Next 3000 · Astro 4321 · Vite/SvelteKit 5173 · Laravel 8000
  port: 3000,

  // Command that boots the site. Delete this line if you start it yourself.
  //   Laravel: "php artisan serve"
  //   PHP:     "php -S localhost:8000 -t public"
  //   Static:  "npx http-server ./dist -p 8080"
  startCommand: "npm run dev",

  // To test a deployed site instead, drop port/startCommand and set:
  // baseURL: "https://staging.example.com",

  // ── Routes to check ───────────────────────────────────────────────────
  // Groups are cumulative: a medium run checks light + medium.
  //   light  → every commit. Your most important pages.
  //   medium → significant layout changes, before merging.
  //   full   → CI / pre-release.
  routes: {
    light: ["/", "/about", "/contact"],
    medium: [],
    full: [],
  },

  // Pages behind a login, custom viewports, ignoring unfixable embeds,
  // and CI setup are all configured here too — see:
  // ${DOCS}
});
`;

const shimTemplate = (lang: Lang): string => `// Generated by \`responsive-overflow-tests init\`. You should not need to edit this.
// All configuration lives in ${CONFIG_BASENAME}.${lang.ext} at the project root.
import { toPlaywrightConfig } from "responsive-overflow-tests";
import config from "./${CONFIG_BASENAME}${lang.importSuffix}";

export default toPlaywrightConfig(config);
`;

const specTemplate = (lang: Lang): string => `// Generated by \`responsive-overflow-tests init\`. You should not need to edit this.
// Routes and options live in ${CONFIG_BASENAME}.${lang.ext} at the project root.
import { test } from "@playwright/test";
import {
  overflowCases,
  authedOverflowCases,
  runOverflowCheck,
  createAuthedPage,
} from "responsive-overflow-tests";
import config from "../${CONFIG_BASENAME}${lang.importSuffix}";

for (const testCase of overflowCases(config)) {
  test(testCase.title, async ({ page }) => {
    await runOverflowCheck(page, testCase, config);
  });
}

const authedCases = authedOverflowCases(config);

if (authedCases.length > 0) {
  test.describe("authenticated", () => {
    for (const testCase of authedCases) {
      test(testCase.title, async ({ browser }) => {
        const page = await createAuthedPage(browser, config);
        try {
          await runOverflowCheck(page, testCase, config);
        } finally {
          await page.context().close();
        }
      });
    }
  });
}
`;

type Result = "created" | "skipped";

function writeIfAbsent(path: string, contents: string): Result {
  if (existsSync(path)) return "skipped";
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  return "created";
}

/** Appends the artifact directory to .gitignore, only if it isn't covered already. */
function ensureGitignore(cwd: string): "updated" | "present" | "created" {
  const path = resolve(cwd, ".gitignore");

  if (!existsSync(path)) {
    writeFileSync(path, `# responsive-overflow-tests / Playwright artifacts\n${ARTIFACT_DIR}\n`);
    return "created";
  }

  const current = readFileSync(path, "utf8");
  const alreadyIgnored = current
    .split(/\r?\n/)
    .map((line) => line.trim())
    .some((line) => line === ARTIFACT_DIR || line === ".playwright");

  if (alreadyIgnored) return "present";

  const separator = current.endsWith("\n") ? "" : "\n";
  writeFileSync(
    path,
    `${current}${separator}\n# responsive-overflow-tests / Playwright artifacts\n${ARTIFACT_DIR}\n`
  );
  return "updated";
}

const PLAYWRIGHT_CONFIG_VARIANTS = [
  "playwright.config.ts",
  "playwright.config.js",
  "playwright.config.mjs",
  "playwright.config.cjs",
];

function init(): void {
  const cwd = process.cwd();
  const lang = detectLang(cwd);

  console.log("\nresponsive-overflow-tests — init\n");

  const existingPlaywrightConfig = PLAYWRIGHT_CONFIG_VARIANTS.find((name) =>
    existsSync(resolve(cwd, name))
  );

  // A config that already imports this package is wired up — most likely our
  // own shim on a re-run. Don't tell the user to merge it with itself.
  const alreadyWired = Boolean(
    existingPlaywrightConfig &&
      readFileSync(resolve(cwd, existingPlaywrightConfig), "utf8").includes(
        "responsive-overflow-tests"
      )
  );

  const targets: { path: string; contents: string }[] = [
    { path: resolve(cwd, `${CONFIG_BASENAME}.${lang.ext}`), contents: configTemplate() },
    { path: resolve(cwd, join("e2e", `overflow.spec.${lang.ext}`)), contents: specTemplate(lang) },
  ];

  if (!existingPlaywrightConfig) {
    targets.unshift({
      path: resolve(cwd, `playwright.config.${lang.ext}`),
      contents: shimTemplate(lang),
    });
  }

  for (const target of targets) {
    const rel = target.path.slice(cwd.length + 1);
    console.log(`  ${writeIfAbsent(target.path, target.contents).padEnd(7)}  ${rel}`);
  }

  if (existingPlaywrightConfig) {
    const note = alreadyWired ? "already wired up" : "already exists — not overwritten";
    console.log(`  skipped  ${existingPlaywrightConfig} (${note})`);
  }

  const gitignore = ensureGitignore(cwd);
  const gitignoreLabel = { created: "created", updated: "updated", present: "ok" }[gitignore];
  const gitignoreNote = {
    created: `created with ${ARTIFACT_DIR}`,
    updated: `added ${ARTIFACT_DIR}`,
    present: `${ARTIFACT_DIR} already ignored`,
  }[gitignore];
  console.log(`  ${gitignoreLabel.padEnd(7)}  .gitignore  (${gitignoreNote})`);

  console.log(
    [
      "",
      `Test artifacts all go to ${ARTIFACT_DIR} — nothing is written anywhere else.`,
      `That line was added to .gitignore above; worth a quick look to confirm it`,
      "landed, especially if you keep ignore rules somewhere non-standard (a global",
      "gitignore, .git/info/exclude, or a monorepo root).",
    ].join("\n")
  );

  if (existingPlaywrightConfig && !alreadyWired) {
    console.log(
      [
        "",
        `You already have ${existingPlaywrightConfig}, so it was left alone. Wire the two together`,
        "by wrapping your export:",
        "",
        '    import { toPlaywrightConfig } from "responsive-overflow-tests";',
        `    import config from "./${CONFIG_BASENAME}${lang.importSuffix}";`,
        "",
        "    export default toPlaywrightConfig(config);",
        "",
        "Or keep your config and just make sure its testDir includes e2e/, and that",
        "baseURL + webServer point at your site.",
        `Details: ${DOCS}#using-an-existing-playwright-config`,
      ].join("\n")
    );
  }

  console.log(
    [
      "",
      "Next steps:",
      "",
      "  1. Install the peer dependency and a browser, if you haven't:",
      "       npm install --save-dev @playwright/test",
      "       npx playwright install chromium",
      "",
      `  2. Open ${CONFIG_BASENAME}.${lang.ext} and set your port and routes.`,
      "",
      "  3. Run it:",
      "       npx playwright test",
      "",
      "  4. Wire it into your own test script, e.g.:",
      '       "scripts": { "test:responsive": "playwright test" }',
      "",
      "Recommended, but yours to set up: run the full tier in CI (on push or",
      "nightly) rather than locally — it is the widest viewport net and the",
      "slowest. Copy-paste workflow:",
      `  ${DOCS}#continuous-integration`,
      "",
      "Working with an AI coding agent? Which tier to run when:",
      `  ${DOCS}#ai-agents--automated-workflows`,
      "",
    ].join("\n")
  );
}

function main(): void {
  const command = process.argv[2];

  if (command === "init") {
    init();
    return;
  }

  console.log(
    [
      "",
      "responsive-overflow-tests",
      "",
      "Usage:",
      "  npx responsive-overflow-tests init",
      "",
      "    Scaffolds responsive-overflow-tests.config.*, a playwright.config.*",
      "    shim, and e2e/overflow.spec.*, and gitignores .playwright/.",
      "    Never overwrites an existing file.",
      "",
      `Docs: ${DOCS}`,
      "",
    ].join("\n")
  );

  if (command && command !== "help" && command !== "--help" && command !== "-h") {
    process.exitCode = 1;
  }
}

main();
